extends: eslint-config-ali/react
parserOptions: 
  typescript: true
parser: babel-eslint
plugins: ['import','react','typescript']
env:
  es6: true
  browser: true
  node: true
  jest: true
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - app
        - router
        - router/modules
rules:
  max-len: 0
  no-nested-ternary: 0
  react/jsx-first-prop-new-line: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
      - '.js'
      - '.jsx'
      - '.tsx'
  import/prefer-default-export: 0
overrides: 
  files: ["*.tsx","*.ts"]
  parser: typescript-eslint-parser
  rules:
      no-undef: 0
      no-restricted-globals: 0
      no-unused-vars: 0
      no-use-before-define: 0
globals: 
  page: true,
  browser: true,
  context: true,
  jestPuppeteer: true,
  defaultTheme: true,
  baseUrl: true
      
