# 所需要替换的 clients 脚本路径列表
swaggers:
    # 后端swagger地址, 本地文件地址或域名url，域名请带上 /v2/api-docs
  - swagger_url: ./swagger.json
    # 显示在通知上的。
    alias:
    # 生成的 client 存放路径
    target_path: ./.jarvis-cache/pmp-sdk.js
# 是否开启强制替换，默认为 false。开启后发现新版本内容后，将自动换成新的版本
forced_replace: false
# 是否开启版本监听，默认为 true
watch_version: false
# api client 生成的类型. 现在仅支持 js ts
target_language: js
# 所依赖的请求代理模块, default： null | superagent
request_lib: superagent
# 是否开启桌面通知, 默认为 true
notification: true
# 操作超时时间，如果需要进行覆盖操作时，提示30秒后仍未操作将继续开启监听任务
timeout: 40000
# 是否需要生成mock文件，默认为false。
need_mock: false

# models存放的文件夹
modelFolder: ./interface

