export const TEXT_ZH_MAP = {
  add: '新增',
  'add charts': '新增图表',
  'edit mode': '编辑模式',
  'config charts': '配置图表',
  'remove charts': '移除图表',
  'export data': '导出数据',
  'save dashboard': '保存大盘',
  'exit edit mode': '取消编辑',
  save: '保存',
  cancel: '取消',
  edit: '编辑',
  delete: '删除',
  ok: '确认',
  move: '移动',
  'exit fullscreen': '退出全屏',
  fullscreen: '全屏查看',
  export: '导出',
  'export picture': '导出图片',
  'confirm to delete': '确认删除',
  'confirm to remove': '确认移除',
  'parameter configuration': '参数配置',
  'common configuration': '通用项配置',
  'datasource configuration': '数据源配置',
  'controls configuration': '控件配置',
  controls: '控件',
  'field name': '字段名',
  select: '选择框',
  'control data': '控件数据',
  value: '值',
  name: '名称',
  action: '操作',
  'confirm to drop data': '已修改，确认退出编辑？',
  title: '标题',
  'chart title': '图表标题',
  'chart description': '图表描述',
  description: '描述',
  showTotal: '显示总量',
  unit: '显示单位',
  'select chart type': '选择图表类型',
  'chart label': '图表标签',
  'show chart label': '显示图表标签',
  'connect null': '连接空值',
  'null display': '空值显示',
  line: '线形图',
  area: '面积图',
  bar: '柱状图',
  pie: '饼图',
  table: '表格',
  metric: '指标',
  'metric aggregation': '指标聚合',
  'metric filter': '指标过滤',
  'failed to get data': '数据获取失败',
  loading: '加载中',
  'show mock data': '模拟数据展示',
  'no chart data': '页面为空,没有图表数据',
  'exporting picture': '正在导出图片...',
  'exporting data': '正在导出数据...',
  'export data error': '导出数据失败！',
  'unnamed dashboard': '未命名大盘',
  'no data': '暂无数据',
  dsl: 'DSL',
  'metrics group': '指标分组',
  'empty metric group tip': '请先选择指标分组！',
  'configuration mode': '配置模式',
  time: '时间',
  'custom time metric': '自定义时间指标',
  'custom time interval': '自定义时间间隔',
  'fixed time range': '固定时间范围',
  expr: '表达式',
  'expr input': '表达式录入',
  'add metric': '添加指标',
  'add value': '添加值',
  'add filter': '添加筛选器',
  dimensions: '维度',
  alias: '别名',
  'alias input': '别名录入',
  'required item': '必填项',
  'uncompleted input': '请完成必填项！',
  'field config': '字段配置',
  'filter config': '过滤器配置',
  'time config': '时间配置',
  'time format': '时间格式',
  second: '秒',
  minute: '分',
  hour: '时',
  day: '天',
  week: '周',
  month: '月',
  'result filter': '结果筛选器',
  'valueDimensions info': '除表格外，其他图表所选值需保证返回值为数值类型！',
  'config err': '配置数据有误，请补全配置！',
};

export const TEXT_EN_MAP = {
  add: 'add',
  'add charts': 'add charts',
  'edit mode': 'edit mode',
  'config charts': 'config charts',
  'remove charts': 'remove charts',
  'export data': 'export as excel',
  'save dashboard': 'save dashboard',
  'exit edit mode': 'exit edit mode',
  save: 'save',
  cancel: 'cancel',
  edit: 'edit',
  delete: 'delete',
  ok: 'ok',
  move: 'move',
  'exit fullscreen': 'exit fullscreen',
  fullscreen: 'fullscreen',
  export: 'export',
  'export picture': 'export picture',
  'confirm to delete': 'confirm to delete',
  'confirm to remove': 'confirm to remove',
  'parameter configuration': 'parameter configuration',
  'common configuration': 'common configuration',
  'datasource configuration': 'datasource configuration',
  'controls configuration': 'controls configuration',
  controls: 'controls',
  'field name': 'field name',
  select: 'select',
  'control data': 'control data',
  value: 'value',
  name: 'name',
  action: 'action',
  'confirm to drop data': 'Modified, confirm to exit edit mode',
  title: 'title',
  'chart title': 'chart title',
  'chart description': 'chart description',
  description: 'description',
  showTotal: 'show total num',
  unit: 'unit',
  'select chart type': 'select chart type',
  'chart label': 'chart label',
  'show chart label': 'show chart label',
  'null display': 'null display',
  'connect null': 'connect null value',
  line: 'line',
  area: 'area',
  bar: 'bar',
  pie: 'pie',
  table: 'table',
  metric: 'metric',
  'metric aggregation': 'metric aggregation',
  'metric filter': 'metric filter',
  'failed to get data': 'failed to get data',
  loading: 'loading',
  'show mock data': 'show mock data',
  'no chart data': 'no chart data',
  'exporting picture': 'exporting picture...',
  'exporting data': 'exporting data...',
  'export data error': 'export data error!',
  'no data': 'no data',
  dsl: 'DSL',
  'metrics group': 'metrics group',
  'empty metric group tip': 'Please select metric group first!',
  'configuration mode': 'configuration mode',
  time: 'time',
  'custom time metric': 'custom time metric',
  'custom time interval': 'custom time interval',
  'fixed time range': 'fixed time range',
  expr: 'expression',
  'expr input': 'expression input',
  'add metric': 'add metric',
  'add value': 'add value',
  'add filter': 'add filter',
  dimensions: 'dimensions',
  alias: 'alias',
  'alias input': 'alias input',
  'uncompleted input': 'Please complete the required fields!',
  'required item': 'required item',
  'field config': 'field config',
  'filter config': 'filter config',
  'time config': 'time config',
  'time format': 'time format',
  second: 'second',
  minute: 'minute',
  hour: 'hour',
  day: 'day',
  week: 'week',
  month: 'month',
  'result filter': 'result filter',
  'valueDimensions info': 'Except for the table, the selected value of other charts must ensure that the return value is numeric!',
  'config err': 'The configuration data is incorrect, please complete the configuration!',
};

const defaultConfig = {
  description: '',
  hideHeader: true,
  hideReload: true,
  dataSourceType: 'api',
  api: {},
};

export const CHARTS_INIT_CONFIG = {
  'chart:line': {
    ...defaultConfig,
    chartType: 'chart:line',
    title: 'Line Chart',
  },
  'chart:area': {
    ...defaultConfig,
    chartType: 'chart:area',
    title: 'Area Chart',
  },
  'chart:bar': {
    ...defaultConfig,
    chartType: 'chart:bar',
    title: 'Bar Chart',
  },
  'chart:pie': {
    ...defaultConfig,
    chartType: 'chart:pie',
    title: 'Pie Chart',
  },
  'chart:funnel': {
    ...defaultConfig,
    chartType: 'chart:funnel',
    title: 'Funnel Chart',
  },
  'chart:map': {
    ...defaultConfig,
    chartType: 'chart:map',
    title: 'Map Chart',
    staticData: {
      metricData: [{}],
    },
  },
  card: {
    ...defaultConfig,
    title: 'Number Card',
    chartType: 'card',
    config: {},
  },
  table: {
    ...defaultConfig,
    chartType: 'table',
    title: 'Table',
    config: {
      optionProps: {
        isMoreThanOneDay: true,
        moreThanOneDayFormat: 'M/D',
      },
    },
  },
  'chart:scatter': {
    ...defaultConfig,
    chartType: 'chart:scatter',
    title: 'Scatter Chart',
  },
};

export const GRID_LAYOUT_CONFIG = {
  cols: 24,
  rowHeight: 30,
};
